import { EssentialItem, EssentialTemplate, Goal, MonthlyPlan, Subscription, Transaction } from '../types';

export const INITIAL_MONTH_KEY = '2026-09';
export const INITIAL_MONTH_NAME = 'September 2026';

export const INITIAL_PLAN: MonthlyPlan = {
  monthKey: INITIAL_MONTH_KEY,
  monthName: INITIAL_MONTH_NAME,
  availableMoney: 20000,
  allocations: {
    essentials: 3200,
    food: 2100,
    transport: 1050,
    shopping: 800,
    education: 1500,
    personal: 1000,
    bills: 1240,
    savings: 3000,
    emergency: 1000,
    other: 400,
  },
  notes: 'Plan for September: keep food delivery in check and save toward RTX Laptop.',
  updatedAt: '2026-09-01T00:00:00.000Z',
};

export const INITIAL_ESSENTIALS: EssentialItem[] = [
  {
    id: 'ess-1',
    name: 'Oats',
    quantity: '1',
    unit: 'kg',
    estimatedCost: 180,
    actualCost: 180,
    isPurchased: true,
    purchasedDate: '2026-09-03',
    preferredProvider: 'blinkit',
    categoryId: 'essentials',
    monthKey: INITIAL_MONTH_KEY,
  },
  {
    id: 'ess-2',
    name: 'Milk',
    quantity: '7.5',
    unit: 'L',
    estimatedCost: 450,
    isPurchased: false,
    preferredProvider: 'zepto',
    categoryId: 'essentials',
    monthKey: INITIAL_MONTH_KEY,
  },
  {
    id: 'ess-3',
    name: 'Sattu',
    quantity: '500',
    unit: 'g',
    estimatedCost: 120,
    isPurchased: false,
    preferredProvider: 'blinkit',
    categoryId: 'essentials',
    monthKey: INITIAL_MONTH_KEY,
  },
  {
    id: 'ess-4',
    name: 'Paneer',
    quantity: '4',
    unit: 'packs',
    estimatedCost: 400,
    isPurchased: false,
    preferredProvider: 'instamart',
    categoryId: 'essentials',
    monthKey: INITIAL_MONTH_KEY,
  },
  {
    id: 'ess-5',
    name: 'Soap',
    quantity: '2',
    unit: 'bars',
    estimatedCost: 100,
    isPurchased: false,
    preferredProvider: 'amazon',
    categoryId: 'personal',
    monthKey: INITIAL_MONTH_KEY,
  },
  {
    id: 'ess-6',
    name: 'Shampoo',
    quantity: '1',
    unit: 'bottle',
    estimatedCost: 250,
    isPurchased: false,
    preferredProvider: 'blinkit',
    categoryId: 'personal',
    monthKey: INITIAL_MONTH_KEY,
  },
];

export const INITIAL_TEMPLATES: EssentialTemplate[] = [
  {
    id: 'tmpl-1',
    name: 'Milk',
    defaultQuantity: '7.5',
    defaultUnit: 'L',
    estimatedCost: 450,
    preferredProvider: 'zepto',
    categoryId: 'essentials',
  },
  {
    id: 'tmpl-2',
    name: 'Oats',
    defaultQuantity: '1',
    defaultUnit: 'kg',
    estimatedCost: 180,
    preferredProvider: 'blinkit',
    categoryId: 'essentials',
  },
  {
    id: 'tmpl-3',
    name: 'Sattu',
    defaultQuantity: '500',
    defaultUnit: 'g',
    estimatedCost: 120,
    preferredProvider: 'blinkit',
    categoryId: 'essentials',
  },
  {
    id: 'tmpl-4',
    name: 'Paneer',
    defaultQuantity: '4',
    defaultUnit: 'packs',
    estimatedCost: 400,
    preferredProvider: 'instamart',
    categoryId: 'essentials',
  },
  {
    id: 'tmpl-5',
    name: 'Toiletries & Cleaning',
    defaultQuantity: '1',
    defaultUnit: 'set',
    estimatedCost: 350,
    preferredProvider: 'amazon',
    categoryId: 'personal',
  },
];

export const INITIAL_TRANSACTIONS: Transaction[] = [
  {
    id: 'tx-1',
    type: 'income',
    amount: 20000,
    categoryId: 'other',
    note: 'Monthly Inflow / Stash for September',
    date: '2026-09-01',
    createdAt: '2026-09-01T09:00:00.000Z',
  },
  {
    id: 'tx-2',
    type: 'expense',
    amount: 200,
    categoryId: 'transport',
    note: 'Metro card recharge',
    merchant: 'Metro',
    date: '2026-09-02',
    createdAt: '2026-09-02T10:15:00.000Z',
  },
  {
    id: 'tx-3',
    type: 'expense',
    amount: 436,
    categoryId: 'essentials',
    note: 'Blinkit monthly oats & supplies',
    merchant: 'Blinkit',
    essentialId: 'ess-1',
    date: '2026-09-03',
    createdAt: '2026-09-03T11:20:00.000Z',
  },
  {
    id: 'tx-4',
    type: 'expense',
    amount: 472,
    categoryId: 'bills',
    note: 'WiFi Broadband monthly bill',
    merchant: 'Airtel',
    date: '2026-09-05',
    createdAt: '2026-09-05T08:00:00.000Z',
  },
  {
    id: 'tx-5',
    type: 'expense',
    amount: 320,
    categoryId: 'food',
    note: "Domino's Pizza treat",
    merchant: "Domino's",
    date: '2026-09-06',
    createdAt: '2026-09-06T20:30:00.000Z',
  },
  {
    id: 'tx-6',
    type: 'expense',
    amount: 80,
    categoryId: 'transport',
    note: 'Rapido bike ride to client meeting',
    merchant: 'Rapido',
    date: '2026-09-07',
    createdAt: '2026-09-07T14:45:00.000Z',
  },
  {
    id: 'tx-7',
    type: 'expense',
    amount: 450,
    categoryId: 'food',
    note: 'Zomato healthy bowl dinner',
    merchant: 'Zomato',
    date: '2026-09-08',
    createdAt: '2026-09-08T21:10:00.000Z',
  },
  {
    id: 'tx-8',
    type: 'expense',
    amount: 600,
    categoryId: 'education',
    note: 'Fullstack Systems book purchase',
    merchant: 'Amazon',
    date: '2026-09-09',
    createdAt: '2026-09-09T16:00:00.000Z',
  },
  {
    id: 'tx-9',
    type: 'expense',
    amount: 50,
    categoryId: 'transport',
    note: 'Metro token to downtown',
    merchant: 'Metro',
    date: '2026-09-10',
    createdAt: '2026-09-10T12:00:00.000Z',
  },
  {
    id: 'tx-10',
    type: 'expense',
    amount: 800,
    categoryId: 'shopping',
    note: 'Ergonomic mousepad and braided cable',
    merchant: 'Amazon',
    date: '2026-09-11',
    createdAt: '2026-09-11T17:25:00.000Z',
  },
  {
    id: 'tx-11',
    type: 'expense',
    amount: 142,
    categoryId: 'food',
    note: 'Chai & evening snacks with team',
    merchant: 'Chai Point',
    date: '2026-09-12',
    createdAt: '2026-09-12T16:10:00.000Z',
  },
  {
    id: 'tx-12',
    type: 'expense',
    amount: 4000,
    categoryId: 'savings',
    note: 'Monthly automatic SIP investment',
    merchant: 'Zerodha',
    date: '2026-09-05',
    createdAt: '2026-09-05T09:00:00.000Z',
  },
];

export const INITIAL_GOALS: Goal[] = [
  {
    id: 'goal-1',
    name: 'RTX Laptop',
    targetAmount: 90000,
    currentAmount: 56700,
    targetDate: '2027-03-31',
    category: 'Hardware & Workstation',
    icon: 'Laptop',
    notes: 'Saving for next-gen machine for graphics, AI, and game dev.',
  },
  {
    id: 'goal-2',
    name: 'Emergency Fund',
    targetAmount: 50000,
    currentAmount: 32000,
    targetDate: '2026-12-31',
    category: 'Safety Net',
    icon: 'Shield',
    notes: '3 months basic cost buffer.',
  },
  {
    id: 'goal-3',
    name: 'Goa Trip / Vacation',
    targetAmount: 25000,
    currentAmount: 14500,
    targetDate: '2027-01-15',
    category: 'Travel & Leisure',
    icon: 'Plane',
    notes: 'Year-end recharge vacation with friends.',
  },
];

export const INITIAL_SUBSCRIPTIONS: Subscription[] = [
  {
    id: 'sub-1',
    name: 'Spotify Premium',
    amount: 119,
    billingCycle: 'monthly',
    dueDay: 13, // Tomorrow relative to Sept 12
    categoryId: 'bills',
    active: true,
  },
  {
    id: 'sub-2',
    name: 'Netflix Standard',
    amount: 149,
    billingCycle: 'monthly',
    dueDay: 18,
    categoryId: 'bills',
    active: true,
  },
  {
    id: 'sub-3',
    name: 'Cloud & AI Subscriptions',
    amount: 500,
    billingCycle: 'monthly',
    dueDay: 25,
    categoryId: 'bills',
    active: true,
  },
  {
    id: 'sub-4',
    name: 'Airtel Broadband Fiber',
    amount: 472,
    billingCycle: 'monthly',
    dueDay: 5,
    categoryId: 'bills',
    active: true,
  },
];
